name: telegram-index-bot
services:
  - name: tg-bot
    type: web
    env:
      - key: TG_API_ID
        value: "123456"
      - key: TG_API_HASH
        value: "your_api_hash"
      - key: TG_SESSION_STRING
        value: "your_long_session_string"
      - key: BOT_TOKEN
        value: "your_bot_token"
      - key: CHANNEL_ID
        value: "-1001234567890"
      - key: WEBHOOK_URL
        value: "https://<your-app>.koyeb.app"
      - key: WEB_PASSWORD
        value: "admin"
    ports:
      - port: 8080
        protocol: http
    build:
      type: docker
    run:
      cmd: uvicorn app:app --host 0.0.0.0 --port 8080
