name: telegram-index-bot

services:
  - name: tgindex
    type: web
    env:
      - key: TG_API_ID
        value: "123456"
      - key: TG_API_HASH
        value: "abcdef123456abcdef123456abcdef12"
      - key: TG_BOT_TOKEN
        value: "123456:ABC-your-bot-token"
      - key: CHANNEL_ID
        value: "-1001234567890"
      - key: WEB_PASSWORD
        value: "changeme"
      - key: SECRET_KEY
        value: "mysecretkey"
    routes:
      - src: /
        dest: /
    docker:
      image: heroku/python
    build:
      builder: heroku/buildpacks:20
      run: |
        pip install -r requirements.txt
    command: uvicorn app:app --host 0.0.0.0 --port ${PORT:-8000}
